### ISSUE TITLE
Adicionar tradução para o inglês

### ISSUE THREAD

**Issue by arvrdnatal** [arvrdnatal/conifer_portfolio#2]
## Info:

- branch: feature/2-add-traducao
- Link para o passo a passo: https://dev.to/joaberamone/traduzir-seu-app-em-flutter-5cbf

## Tasks:

- [x] Adicionar pacote `flutter_localizations`
- [x] Importar biblioteca no MaterialApp
- [x] Adicionar pacote `intl`
- [x] Habilitar o sinalizador de geração
- [x] Adicionar um arquivo l10n.yaml
- [x] Criar pasta l10n
